name= "pastebin-worker"
compatibility_date = "2023-11-28"
account_id= "37d2a5b56518873c54dcdc0e1f96203c"
main = "src/index.ts"
workers_dev = false

vars = { ENVIRONMENT = "production" }
route = { pattern = "paste.430382.xyz", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "9bad3470bfed478690249012796eb33e" },
  { binding = "PBIMGS", id ="f9bcb73a08f74e71bf838e606647f137" }
]

[site]
bucket = "./static/dist"
